# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('no_of_hours', models.IntegerField(default=0)),
                ('job_number_choice', models.IntegerField(default=0)),
            ],
        ),
    ]
